# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KIwgehXWXekcd2oS2hPu1PjOeuCWCCXRcF3ytsro3j9BubFaSn5nPhTEfD9m9LZUxSavZt1HLfhsxP6GlnW4ewUClkbFBSEqMWMxM11brR8Rh1FClcs8jwjlpg7JcAxtyBWAzWuYn+snmqhlLtFAxK4Bif3yMlN6SFOLEKMYGtacxWq/f/2HuTaBoNsKWoa/wD738W+Qnlw7DcY4DrYesVpL+gg8vQO5SzVTHQ7FSSvGYR/n5BQP9j8oCu4Ib+IAUu0clLrhnqXYlW9ArkVX7y0lI3n/7nw6DBPkaTacaf4uCkvqfMn++NlnW6epTmKJvLqa7NWF8eALy1Dk7VBHtNablLzHlsmO2r/Q/DU3PicTVWlQ+77kk80WBXukh2RSejw7GG6tX9mQYg5F++YzENldHKtCL0mtHel/I35kqatgBZpkMoBkj5Ftu569+hbB+KTbxa/sg7Mv9gWOwhTW7d8WGvnycDHV/nuT4OtynPqvLYVYFTzdr2kB2jtvcq5OkvrCw8di1TdPa6JEo43Ktn4146hXSQqsfnqVVNjZQGHDgl7YJ8DT41DJYFqwNVgOrpJvUEzYOfNm3Yoa3CHihgBUKwoF5cRjDKaNcJYxTcQUTIqUTm5f+gyMdGNiey+ZcaTbHsjeQW53Xc++7VlyL+eOq26RAiEPzcLd5ZpPhEI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
