travis:
  secure:
    BINSTAR_TOKEN: YgyE22wSAQeOQwhx6dMXk2+BMLG7Jj8G5rn9nyccISg4ngxBe0zmhUZDqxPmkYyd4RYpzKt3uhL1vhk6jP7q0yCHpI9wMppdcnd3Ir0+Nf4Gm7PFQ8wK/NPQEmcvzr4P22p4rdvT8kl9IOol2eMKbOjolmrYRtSpXDxnHlRZbiXflne3YvoB5zjy+QbjZGQ6Evhrgrrmja9I8AvSh/cLAe+SRLpW+ldQ15MAS9s2jq0dgZ1rMXX3kOjy4EGP90Cdk8/QhffbpkGqyBl2H0YQm6K7Z/PJgTsRB6R8bo5dohofITUFprVp1QnCi3S1MtCdt3cgBSNu8LTMCIh2Wj6LM+iRauVqahX2bJwv2psMtUaxtB8jxITfPpNp5TjMsWmAxrRe8OV1hCQpWzrR/aiYcI9Ayr2tPNNjGd2SNyotHdeJzITr3mE56XS6ik7a9+uO14pJUMtZDB2MLChpOcoSU7dqUbGDbD6wNetAw2ES+L2Jt6L0TtZ8p3Yfxz0tgjHcQLKBGu/iK1lGhl6jtP12xTF38ItJOH45GLaPdxkaHeR++XCtdO0ECMFdYxPd9Lip2SXmbb3Zpv/HrBWq6i0y2zeCHmz2DK7NbGnf9wsXcD2vtJAj8YqsECNW/XanCzztHWFSPvYd0VjzRe3tU6MmM5FwWqoQsLWDT7ZmIgJzEdM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
