travis:
  secure:
    BINSTAR_TOKEN: KIwgehXWXekcd2oS2hPu1PjOeuCWCCXRcF3ytsro3j9BubFaSn5nPhTEfD9m9LZUxSavZt1HLfhsxP6GlnW4ewUClkbFBSEqMWMxM11brR8Rh1FClcs8jwjlpg7JcAxtyBWAzWuYn+snmqhlLtFAxK4Bif3yMlN6SFOLEKMYGtacxWq/f/2HuTaBoNsKWoa/wD738W+Qnlw7DcY4DrYesVpL+gg8vQO5SzVTHQ7FSSvGYR/n5BQP9j8oCu4Ib+IAUu0clLrhnqXYlW9ArkVX7y0lI3n/7nw6DBPkaTacaf4uCkvqfMn++NlnW6epTmKJvLqa7NWF8eALy1Dk7VBHtNablLzHlsmO2r/Q/DU3PicTVWlQ+77kk80WBXukh2RSejw7GG6tX9mQYg5F++YzENldHKtCL0mtHel/I35kqatgBZpkMoBkj5Ftu569+hbB+KTbxa/sg7Mv9gWOwhTW7d8WGvnycDHV/nuT4OtynPqvLYVYFTzdr2kB2jtvcq5OkvrCw8di1TdPa6JEo43Ktn4146hXSQqsfnqVVNjZQGHDgl7YJ8DT41DJYFqwNVgOrpJvUEzYOfNm3Yoa3CHihgBUKwoF5cRjDKaNcJYxTcQUTIqUTm5f+gyMdGNiey+ZcaTbHsjeQW53Xc++7VlyL+eOq26RAiEPzcLd5ZpPhEI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
