travis:
  secure:
    BINSTAR_TOKEN: Y8+lqllmIDdHuxMWn5Mv0iwLgENm6RoVJy+CgJwOfkBK7aZmBR5Kdx8b4Syfp1yqUB03miVi8+iawecRm2J4mlIu/eaUW4TBlMu7Crn/3AzHPrXlDRUxWvvqMv43ytk0fht74T5khLuQ9vU5bIrMZv9GC9xecOxOVBjl2S4YBJWUpqs+mJN3WWf9Q4R1Rl2bZDyJil5KSGv3xkR+GREg+yND1x9APB+xtprrG7p00UYyjHCkm2CX4BoOIF099fmzeO5vSgjPPr1xidoogCjbFZYGkWIBbA3c2WEzxUqGnSd5bhgn82rItBhyjp705SbpTg+n2zaCIKTaBMEDPQ5RUw9f0MmfyTdImyit5MFG492c6djTIbynzgTewVlo6RMSmGaqMwwrLC+rme8pM18fjeMpIsXaWGnzqJCFMshyBXb4ZXJ/OpoaP1Yqfxq5EkzzPPwfGUwcpVDMJSpmq5KygplU7V/yQ6GZZmtMC5s7peFb61iMu0nFPPPoH3bS1IwbDRGFC0W7Rkuvlj9OjoZX7EAlcV+0eCA2oFEEGIvehXqFfcb5pm1MjkRCY1shSwz44uEUPm26j7sXtNsSI+H6PC87TKqZSR1PULE6zCx/ndqOYCDYzxmAE0n3wrPU2XLz28s0ZNEFqgSx7ufGvtLIgx11fapYdR4cu+Bp7VCklPI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
